In [221]:
import pandas as pd


In [222]:
import numpy as np

In [223]:
a = np.random.random((2,3,5))
print(a)

[[[0.21244631 0.50830658 0.13074858 0.63438582 0.62322185]
  [0.58802629 0.41584101 0.24927985 0.53481857 0.47820442]
  [0.56104291 0.35490614 0.82777268 0.61692704 0.18160294]]

 [[0.21582824 0.03868271 0.88500024 0.05012774 0.68318311]
  [0.73511714 0.44341241 0.81081787 0.81684801 0.13822353]
  [0.21007504 0.64976996 0.10536429 0.78916659 0.63209795]]]


In [224]:
a.shape


(2, 3, 5)

In [225]:
b.shape

(5, 2, 3)

In [226]:
c = b.transpose(1,2,0)
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [227]:
print(a)

[[[0.21244631 0.50830658 0.13074858 0.63438582 0.62322185]
  [0.58802629 0.41584101 0.24927985 0.53481857 0.47820442]
  [0.56104291 0.35490614 0.82777268 0.61692704 0.18160294]]

 [[0.21582824 0.03868271 0.88500024 0.05012774 0.68318311]
  [0.73511714 0.44341241 0.81081787 0.81684801 0.13822353]
  [0.21007504 0.64976996 0.10536429 0.78916659 0.63209795]]]


In [228]:
a = np.random.random((2,3,5))
a

array([[[0.75782995, 0.35641663, 0.84400035, 0.2901856 , 0.25465543],
        [0.97832219, 0.46121397, 0.24592745, 0.50699349, 0.46625787],
        [0.7582699 , 0.70705067, 0.99314309, 0.80048535, 0.98273344]],

       [[0.72091365, 0.83255083, 0.96379847, 0.70255472, 0.51132975],
        [0.59423894, 0.15918647, 0.90163304, 0.36916794, 0.68104819],
        [0.37484758, 0.01632901, 0.6092948 , 0.21461584, 0.94938717]]])

In [229]:
d_min = d.min()

In [230]:
d_max = d.max()

In [231]:
d_mean = d.mean()

In [258]:
f = np.empty((2,3,5))

In [268]:
for x in range(2):
    for y in range (3):
        for i in range(5):
            if d_min < d[x,y,i] < d_mean:
                f[x,y,i] = 25
            elif d_mean < d[x,y,i] < d_max:
                f[x,y,i] = 75
            elif d[x,y,i] == d_mean:
                f[x,y,i] = 50
            elif d[x,y,i] == d_min:
                f[x,y,i] = 0
            elif d[x,y,i] == d_max:
                f[x,y,i] = 100                   

In [269]:
print(f)

[[[ 75.  75.  25.  25.  25.]
  [ 75. 100.  75.  25.  25.]
  [ 25.  25.  25.  75.  25.]]

 [[ 75.  25.  25.  25.  75.]
  [ 75.  75.  75.  75.  75.]
  [ 25.  25.  25.   0.  75.]]]


In [290]:
g = np.empty((2,3,5), str)

In [291]:
for x in range(2):
    for y in range (3):
        for i in range(5):
            if f[x,y,i] == 0:
                g[x,y,i] = "A"
            elif f[x,y,i] == 25:
                g[x,y,i] = "B"
            elif f[x,y,i] == 50:
                g[x,y,i] = "C"
            elif f[x,y,i] == 75:
                g[x,y,i] = "D"
            elif f[x,y,i] == 100:
                g[x,y,i] = "E"

In [292]:
print(g)

[[['D' 'D' 'B' 'B' 'B']
  ['D' 'E' 'D' 'B' 'B']
  ['B' 'B' 'B' 'D' 'B']]

 [['D' 'B' 'B' 'B' 'D']
  ['D' 'D' 'D' 'D' 'D']
  ['B' 'B' 'B' 'A' 'D']]]


In [193]:
for x in arr3:
    print(arr3[0])

[[11 12 13 14]
 [13 14 15 19]]
[[11 12 13 14]
 [13 14 15 19]]
[[11 12 13 14]
 [13 14 15 19]]
