In [1]:
import numpy as np


In [6]:
a = np.random.random(size=(2,3,5))
a

array([[[3.38441719e-01, 8.97076145e-03, 3.15730257e-01, 1.54035395e-01,
         8.61249809e-01],
        [3.62030222e-01, 4.36635932e-01, 2.59512547e-01, 9.97900035e-01,
         1.72948654e-01],
        [5.73544428e-01, 2.22014645e-01, 2.92385456e-01, 1.06518658e-01,
         7.13068160e-01]],

       [[6.13415936e-01, 5.26127240e-01, 6.91990176e-01, 4.30191790e-01,
         5.35734771e-01],
        [6.22115125e-01, 3.92722306e-01, 9.32885557e-05, 3.60096466e-01,
         9.64740246e-01],
        [7.47934089e-02, 3.05673896e-01, 1.02903441e-01, 4.62049003e-01,
         4.55167767e-02]]])

In [3]:
np.random.random()

0.37537352148955216

In [8]:
a =np.array([[[np.random.random() for i in range(5)]for ii in range(3)]for iii in range(2)])
a

array([[[0.17984252, 0.15115371, 0.34848211, 0.52976808, 0.55915387],
        [0.13027021, 0.75272914, 0.95035726, 0.29969737, 0.66988488],
        [0.06604998, 0.85706644, 0.77366135, 0.56670951, 0.56946374]],

       [[0.57436302, 0.80005093, 0.08416949, 0.48930485, 0.39377062],
        [0.10499631, 0.49694593, 0.31487701, 0.33140939, 0.12812411],
        [0.84657517, 0.98062036, 0.20041548, 0.95162855, 0.44985349]]])

In [10]:
b = np.ones(shape=(5,2,3))
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [17]:
print(list(i for i in dir(b) if '__' not in i))

['T', 'all', 'any', 'argmax', 'argmin', 'argpartition', 'argsort', 'astype', 'base', 'byteswap', 'choose', 'clip', 'compress', 'conj', 'conjugate', 'copy', 'ctypes', 'cumprod', 'cumsum', 'data', 'diagonal', 'dot', 'dtype', 'dump', 'dumps', 'fill', 'flags', 'flat', 'flatten', 'getfield', 'imag', 'item', 'itemset', 'itemsize', 'max', 'mean', 'min', 'nbytes', 'ndim', 'newbyteorder', 'nonzero', 'partition', 'prod', 'ptp', 'put', 'ravel', 'real', 'repeat', 'reshape', 'resize', 'round', 'searchsorted', 'setfield', 'setflags', 'shape', 'size', 'sort', 'squeeze', 'std', 'strides', 'sum', 'swapaxes', 'take', 'tobytes', 'tofile', 'tolist', 'tostring', 'trace', 'transpose', 'var', 'view']


In [23]:
print(b.size)
print(a.size)

30
30


In [37]:
print(b.transpose().shape)
print(a.shape)

(3, 2, 5)
(2, 3, 5)


In [30]:
help(b.transpose)

Help on built-in function transpose:

transpose(...) method of numpy.ndarray instance
    a.transpose(*axes)
    
    Returns a view of the array with axes transposed.
    
    For a 1-D array this has no effect, as a transposed vector is simply the
    same vector. To convert a 1-D array into a 2D column vector, an additional
    dimension must be added. `np.atleast2d(a).T` achieves this, as does
    `a[:, np.newaxis]`.
    For a 2-D array, this is a standard matrix transpose.
    For an n-D array, if axes are given, their order indicates how the
    axes are permuted (see Examples). If axes are not provided and
    ``a.shape = (i[0], i[1], ... i[n-2], i[n-1])``, then
    ``a.transpose().shape = (i[n-1], i[n-2], ... i[1], i[0])``.
    
    Parameters
    ----------
    axes : None, tuple of ints, or `n` ints
    
     * None or no argument: reverses the order of the axes.
    
     * tuple of ints: `i` in the `j`-th place in the tuple means `a`'s
       `i`-th axis becomes `a.transpos

In [39]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a",
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?
a = np.random.random(size=(2,3,5)) # La mas facil
a_1 = np.array([[[np.random.random() for i in range(5)]for ii in range(3)]for iii in range(2)]) # Usando list comprehension

# can't thing of a third way 

#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"
b = np.ones(shape=(5,2,3))




#7. Do a and b have the same size? How do you prove that in Python code?
# They have diferents shapes but should have the same size, let's check it,


#8. Are you able to add a and b? Why or why not?
# No, they have different shapes so you shouldn't be able to add a and b,
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".
c = b.transpose(1,2,0) 

#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?
try: 
        d = a+c
        #print('a+c= ', d) # now we can add them as they have the same shape 
except ValueError:
        print(f'Can not add a and c as they have different shapes. Shape of a: {a.shape}, shape of c: {c.shape}.')

#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.

#12. Multiply a and c. Assign the result to e.
e = a*c
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"

d_max = d.max()
d_min = d.min()
d_mean = d.mean()

#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.
f = np.empty(shape=(2,3,5))



In [57]:
print(f.shape)

(2, 3, 5)


In [58]:
i , j, k = -1 , -1 , -1 
for Dim1 in d:
    i += 1
    for  Dim2 in Dim1:
        j += 1
        for ele in Dim2:
            k += 1
            if d_min < ele < d_mean:
                f[i][j][k] = 25
            elif d_mean < ele < d_max:
                f[i][j][k] = 75
            elif ele == d_mean:
                f[i][j][k] = 50
            elif ele == d_min:
                f[i][j][k] = 0
            elif ele == d_max:
                f[i][j][k] = 100
            k = -1
    j = -1
    
print(f)

[[[7.50000000e+01 1.70929143e+00 1.76109021e+00 1.86534411e+00
   1.60470174e+00]
  [2.50000000e+01 6.71313957e-02 2.63219072e-01 7.34943100e-01
   4.05182985e-01]
  [2.50000000e+01 8.51451974e-02 3.53468720e-01 7.28049057e-01
   6.48232472e-01]]

 [[7.50000000e+01 7.65283805e-02 3.58049156e-01 2.10216567e-01
   3.27994438e-01]
  [7.50000000e+01 4.34005152e-01 2.90468753e-01 8.10054437e-01
   6.02541360e-01]
  [2.50000000e+01 2.63774538e-01 9.96696166e-01 8.42970939e-01
   2.73800358e-02]]]
